channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=23.2.1
- pip:
  - mlflow==2.4
  - cloudpickle==2.2.1
  - numpy==1.25.1
  - psutil==5.9.4
  - scikit-learn==1.2.2
  - scipy==1.11.1
name: mlflow-env
